Fix problems introduced by 'addressing CR comments'
Well, while these things were in the sausage-long if(), it would have
short-circuited before hitting the Object.equals(Object) call...

however, now that i extracted all of these comparisons into individual booleans,
i still need to retain the shortcircuiting logic. So, that also needs to be added.

This should resolve the following crash stacktrace:
```
ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "com.fs.starfarer.api.combat.ShipAPI.getParentStation()" is null
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "com.fs.starfarer.api.combat.ShipAPI.getParentStation()" is null
    at data.scripts.hullmods.vayra_modular_shields.findGenerator(vayra_modular_shields.java:188) ~[?:?]
    at data.scripts.hullmods.vayra_modular_shields.advanceInCombat(vayra_modular_shields.java:141) ~[?:?]
    at com.fs.starfarer.combat.entities.Ship.advance(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.combat.CombatState.traverse(Unknown Source) ~[port_obf.jar:?]
    at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
    at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
    at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```