Fix crashes in colonial manager and AOTD compatibility patch (#49)
* Null-safety fixes in VayraColonialManager

Turns out, there was a block that just assumed that some factions will *always* be there
and will never return null before attempting to change their relationship towards some other faction.

Well, this particular crashlog says otherwise:
2595808 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.campaign.FactionAPI.setRelationship(String, float)" because the return value of "com.fs.starfarer.api.campaign.SectorAPI.getFaction(String)" is null
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.campaign.FactionAPI.setRelationship(String, float)" because the return value of "com.fs.starfarer.api.campaign.SectorAPI.getFaction(String)" is null
        at data.scripts.campaign.colonies.VayraColonialManager.<init>(VayraColonialManager.java:125) ~[?:?]
        at data.scripts.VayraMergedModPlugin.onNewGameAfterTimePass(VayraMergedModPlugin.java:332) ~[?:?]
        at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source) ~[port_obf.jar:?]

So, null-guard everything and make it safe so it least it doesn't crash. And the two new methods -
safeChangeRelationshipForFaction() and safeGetRelationshipForFactionToFaction() should do.
The rest of the changes are just necessary baggage for it to look alright and work out fine.

* Potential AOTD compatibiltiy fix and parametrize the console log spam

The AOTD compatibility is still there, but the console log spam is parametrized with
two new flags - SPAM_LOG_ENABLED (currently 'true') and SPAM_LOG_SPAMS_CONSOLE (currently 'false')

They are fed to a new spamLog() method which either forwards their message to console or log depending
on the flags.

* Latest JAR

* Add LunaSettings and the new flag to VayraColonialManager

The settings should contain only one thing so far, but the whole 'architecture' was
setup alright to allow for future extensibility.

VayraColonialManager also got the new UPGRADES_DISABLED flag too, defaulting to 'false'
both in the java code, and the LunaSettings.csv

EDIT: added a semicolon where it was missing
EDIT2: fixed the icon in LunaSettings too and everything is hooked up properly.

* Delete unnecessary png and add latest JAR