Fix Vayra's bad use of DerelictShipEntityPlugin::pickVariant()
So, one user reported a crash with teh following stacktrace:
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Float (java.lang.String and java.lang.Float are in module java.base of loader 'bootstrap')
    at com.fs.starfarer.api.impl.campaign.DerelictShipEntityPlugin.pickVariant(DerelictShipEntityPlugin.java:190) ~[starfarer.api.jar:?]
    at data.scripts.campaign.events.VayraGhostShipDistressCall.spawnWreck(VayraGhostShipDistressCall.java:90) ~[?:?]
    at data.scripts.campaign.events.VayraGhostShipDistressCall.setup(VayraGhostShipDistressCall.java:65) ~[?:?]
    at data.scripts.campaign.events.VayraGhostShipDistressCall.advance(VayraGhostShipDistressCall.java:46) ~[?:?]
    at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.BaseGameState.traverse(Unknown Source) ~[port_obf.jar:?]
    at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
    at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
    at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]

It's caused by the obvious bad usage of the pickVariant() method, and unfortunatelly, the crash
is to be expected 100% of the time.

Namely, Vayra was doing this:
            variantId = pickVariant(faction, new Random(),
                    ShipRoles.COMBAT_LARGE,
                    ShipRoles.COMBAT_CAPITAL,
                    ShipRoles.COMBAT_CAPITAL,
                    ShipRoles.CARRIER_MEDIUM,
                    ShipRoles.CARRIER_LARGE
            );

but the DerelictShipEntityPlugin::pickVariant() actually does this in it's implementation:
    public static String pickVariant(String factionId, Random random, Object ... shipRoles) {
        /* snip */
        WeightedRandomPicker<String> picker = new WeightedRandomPicker<String>(random);
        for (int i = 0; i < shipRoles.length; i += 2) {
            String role = (String) shipRoles[i];
            Float weight = (Float) shipRoles[i + 1];  //crashes here
            picker.add(role, weight);
        }

which means, we can't simply pass a vararg of strings to it, we need to pass a mixed-list of
String shipRole followed by it's weight.

In lack of better ideas, i just removed the duplicated calls and assigned the duplicated roles a weight of 2.
Hopefully that resolves the problem satifactorily.