Fix bug in modular shields fix (#57)
* Fix problems introduced by 'addressing CR comments'

Well, while these things were in the sausage-long if(), it would have
short-circuited before hitting the Object.equals(Object) call...

however, now that i extracted all of these comparisons into individual booleans,
i still need to retain the shortcircuiting logic. So, that also needs to be added.

This should resolve the following crash stacktrace:
```
ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "com.fs.starfarer.api.combat.ShipAPI.getParentStation()" is null
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "com.fs.starfarer.api.combat.ShipAPI.getParentStation()" is null
    at data.scripts.hullmods.vayra_modular_shields.findGenerator(vayra_modular_shields.java:188) ~[?:?]
    at data.scripts.hullmods.vayra_modular_shields.advanceInCombat(vayra_modular_shields.java:141) ~[?:?]
    at com.fs.starfarer.combat.entities.Ship.advance(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.combat.CombatState.traverse(Unknown Source) ~[port_obf.jar:?]
    at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
    at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
    at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```

* Double the capacity of caliph shield parts and new JAR

So, instead of the generator having capacity of 20k flux and the shield parts having 10k each,
that's now doubled to 40k for the generator and 20k for shield parts. Should make the shield
twice as durable.

Also new JAR.

* Hide vayra_modular_shields logs behind VAYRA_DEBUG and new JAR

They were spamming too much for no real reason, but they're behind the flag now.

* Latest JAR after merge