Issue #104 - fix weird crash in hyperspace while colonial factions are picking targets (#105)
Apparently, there is something weird going on in this portion of the code:
```
            Vector2f sourceLoc = source.getLocationInHyperspace();
            SectorEntityToken dest = system.getHyperspaceAnchor();
            Vector2f destLoc = dest.getLocationInHyperspace();
```

Turns out, `dest` ended up being null? So, lets null-guard it, and keep on searching
when it ends up being null.

Issue link:
https://github.com/RkShaRkz/Starsector-IntelliJ-Template/issues/104

Stacktrace:
```
ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.campaign.SectorEntityToken.getLocationInHyperspace()" because "dest" is null
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.campaign.SectorEntityToken.getLocationInHyperspace()" because "dest" is null
    at data.scripts.campaign.colonies.VayraColonialManager.pickTarget(VayraColonialManager.java:870)
    at data.scripts.campaign.colonies.VayraColonialManager.performColonySpawn(VayraColonialManager.java:353)
    at data.scripts.campaign.colonies.VayraColonialManager.advance(VayraColonialManager.java:306)
    at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source)
    at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source)
    at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
    at com.fs.state.AppDriver.begin(Unknown Source)
    at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
    at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
    at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
```