Try to fix a VayraPersonBountyManager NPE(s) that occassionally happens during sector generation (#90)
* Try to fix a VayraPersonBountyManager NPE that occassionally happens during sector generation

There was a VayraPersonBountyManager.getInstance() case where it legitimately can and will be null.

This commit attempts to take care of the following stacktrace
```
921719 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.impl.campaign.intel.PersonBountyManager.getActive()" because the return value of "com.fs.starfarer.api.impl.campaign.intel.PersonBountyManager.getInstance()" is null
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.impl.campaign.intel.PersonBountyManager.getActive()" because the return value of "com.fs.starfarer.api.impl.campaign.intel.PersonBountyManager.getInstance()" is null
        at data.scripts.campaign.intel.VayraPersonBountyManager.advance(VayraPersonBountyManager.java:329)
        at data.scripts.VayraMergedModPlugin.onNewGameAfterTimePass(VayraMergedModPlugin.java:373)
        at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source)
        at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source)
        at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source)
        at com.fs.starfarer.ui.oo0O.dismiss(Unknown Source)
        at com.fs.starfarer.ui.newui.M.dismiss(Unknown Source)
        at com.fs.starfarer.ui.newui.o0Oo.advanceImpl(Unknown Source)
        at com.fs.starfarer.ui.OOOo.advance(Unknown Source)
        at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
        at com.fs.starfarer.ui.OOOo.advance(Unknown Source)
        at com.fs.starfarer.title.TitleScreenState.advance(Unknown Source)
        at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
        at com.fs.state.AppDriver.begin(Unknown Source)
        at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
        at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
        at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

* Improve the nullguarding of PersonBountyManager.getInstance() call

It just occured to me that nullguarding the call itself might not fix the problem
because the shitty `PersonBountyManager.getInstance()` might return null between two
calls, which shouldn't be happening but this is Alex's Starsector API after all.

So, grab the instance into a variable and then nullguard that thing. That will cause it
to not mutate between two different getInstance() calls and should be safer.

* Issue 82 - address race-condition induced NPE in VayraPersonBountyIntel

There is a race-condition when a bounty is picked, and everything goes well up until the
commander should receive his skills, by using the `FleetFactoryV3.addCommanderSkills(...)`
call, which is when the Starsector API tries getting all of those skills and getting the skills
out of the assigned SkillLevels (or some such).

Then the following crash (stacktrace) happens because the skills haven't finished loading yet.

Attaching the debugger slows down the code so it's impossible to catch.
Adding logs to see what's going wrong slows down the code so it's impossible to catch.
This commit completely resolves the issue, by putting it behind a try/catch clause which logs the problem when it happens,
but it also seems that the problem has magically vanished completely since nothing gets logged.

Issue link:
https://github.com/RkShaRkz/Starsector-IntelliJ-Template/issues/82

```
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.loading.SkillSpec.isAptitudeEffect()" because the return value of "com.fs.starfarer.campaign.CharacterStats$SkillLevel.getSkill()" is null
	at com.fs.starfarer.campaign.CharacterStats.refreshCharacterStatsEffects(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.CharacterStats.refreshCharacterStatsEffects(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.api.impl.campaign.fleets.FleetFactoryV3.addCommanderSkills(FleetFactoryV3.java:1192) ~[starfarer.api.jar:?]
	at com.fs.starfarer.api.impl.campaign.fleets.FleetFactoryV3.addCommanderSkills(FleetFactoryV3.java:1904) ~[starfarer.api.jar:?]
	at data.scripts.campaign.intel.VayraPersonBountyIntel.spawnFleet(VayraPersonBountyIntel.java:1081) ~[?:?]
	at data.scripts.campaign.intel.VayraPersonBountyIntel.<init>(VayraPersonBountyIntel.java:206) ~[?:?]
	at data.scripts.campaign.intel.VayraPersonBountyManager.createEvent(VayraPersonBountyManager.java:359) ~[?:?]
	at data.scripts.campaign.intel.VayraPersonBountyManager.advance(VayraPersonBountyManager.java:333) ~[?:?]
	at data.scripts.VayraMergedModPlugin.onNewGameAfterTimePass(VayraMergedModPlugin.java:373) ~[?:?]
	at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.O.dismiss(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.impl.for.dismiss(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.save.if.actionPerformed(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o0O0.buttonPressed(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.int.Ò00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.int.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.W.o00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source) ~[port_obf.jar:?]
	at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```

* Latest JAR with these changes

* Add stacktraces to error logs produced by VayraPersonBountyIntel

So that when the catch() clause does print something - we get to see what happened where.

Also latest JAR.

* Addressing own CR comments - add the warning log about vanilla bounty manager being null

* Latest JAR