Issue 82 - address race-condition induced NPE in VayraPersonBountyIntel
There is a race-condition when a bounty is picked, and everything goes well up until the
commander should receive his skills, by using the `FleetFactoryV3.addCommanderSkills(...)`
call, which is when the Starsector API tries getting all of those skills and getting the skills
out of the assigned SkillLevels (or some such).

Then the following crash (stacktrace) happens because the skills haven't finished loading yet.

Attaching the debugger slows down the code so it's impossible to catch.
Adding logs to see what's going wrong slows down the code so it's impossible to catch.
This commit completely resolves the issue, by putting it behind a try/catch clause which logs the problem when it happens,
but it also seems that the problem has magically vanished completely since nothing gets logged.

Issue link:
https://github.com/RkShaRkz/Starsector-IntelliJ-Template/issues/82

```
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.loading.SkillSpec.isAptitudeEffect()" because the return value of "com.fs.starfarer.campaign.CharacterStats$SkillLevel.getSkill()" is null
	at com.fs.starfarer.campaign.CharacterStats.refreshCharacterStatsEffects(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.CharacterStats.refreshCharacterStatsEffects(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.api.impl.campaign.fleets.FleetFactoryV3.addCommanderSkills(FleetFactoryV3.java:1192) ~[starfarer.api.jar:?]
	at com.fs.starfarer.api.impl.campaign.fleets.FleetFactoryV3.addCommanderSkills(FleetFactoryV3.java:1904) ~[starfarer.api.jar:?]
	at data.scripts.campaign.intel.VayraPersonBountyIntel.spawnFleet(VayraPersonBountyIntel.java:1081) ~[?:?]
	at data.scripts.campaign.intel.VayraPersonBountyIntel.<init>(VayraPersonBountyIntel.java:206) ~[?:?]
	at data.scripts.campaign.intel.VayraPersonBountyManager.createEvent(VayraPersonBountyManager.java:359) ~[?:?]
	at data.scripts.campaign.intel.VayraPersonBountyManager.advance(VayraPersonBountyManager.java:333) ~[?:?]
	at data.scripts.VayraMergedModPlugin.onNewGameAfterTimePass(VayraMergedModPlugin.java:373) ~[?:?]
	at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.O.dismiss(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.impl.for.dismiss(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.save.if.actionPerformed(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o0O0.buttonPressed(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.int.Ò00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.int.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.W.o00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source) ~[port_obf.jar:?]
	at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```