Rename Vayra's "drone_pd" ship system to vayra_exemplardrone_drone_pd
Issue link:
https://github.com/RkShaRkz/Starsector-IntelliJ-Template/issues/74

Turns out, the 'old' name was just trampling the original/vanilla drone_pd system's file,
but used a different ID - vayra_exemplardrone_drone - so that when any other ships tried to use it
the game would just crash with a `RuntimeException: System with id [drone_pd] not found`

This commit should solve the following stacktrace:
```
ERROR com.fs.starfarer.combat.CombatMain  - java.lang.RuntimeException: System with id [drone_pd] not found
java.lang.RuntimeException: System with id [drone_pd] not found
	at com.fs.starfarer.combat.entities.Ship.<init>(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.loading.specs.oooo.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.fleet.FleetMember.instantiateForCombat(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatFleetManager.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatFleetManager.Ò00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatFleetManager.deploy(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.ai.admiral.oOoO.if.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.ai.admiral.oOoO.Òo0000(Unknown Source) ~[port_obf.jar:?]
	. . . . .
```