Try to fix a VayraPersonBountyManager NPE that occassionally happens during sector generation
There was a VayraPersonBountyManager.getInstance() case where it legitimately can and will be null.

This commit attempts to take care of the following stacktrace
```
921719 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.impl.campaign.intel.PersonBountyManager.getActive()" because the return value of "com.fs.starfarer.api.impl.campaign.intel.PersonBountyManager.getInstance()" is null
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.impl.campaign.intel.PersonBountyManager.getActive()" because the return value of "com.fs.starfarer.api.impl.campaign.intel.PersonBountyManager.getInstance()" is null
        at data.scripts.campaign.intel.VayraPersonBountyManager.advance(VayraPersonBountyManager.java:329)
        at data.scripts.VayraMergedModPlugin.onNewGameAfterTimePass(VayraMergedModPlugin.java:373)
        at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source)
        at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source)
        at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source)
        at com.fs.starfarer.ui.oo0O.dismiss(Unknown Source)
        at com.fs.starfarer.ui.newui.M.dismiss(Unknown Source)
        at com.fs.starfarer.ui.newui.o0Oo.advanceImpl(Unknown Source)
        at com.fs.starfarer.ui.OOOo.advance(Unknown Source)
        at com.fs.starfarer.ui.interfacenew.advanceImpl(Unknown Source)
        at com.fs.starfarer.ui.OOOo.advance(Unknown Source)
        at com.fs.starfarer.title.TitleScreenState.advance(Unknown Source)
        at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
        at com.fs.state.AppDriver.begin(Unknown Source)
        at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
        at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
        at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```