Null-safety fixes in VayraColonialManager
Turns out, there was a block that just assumed that some factions will *always* be there
and will never return null before attempting to change their relationship towards some other faction.

Well, this particular crashlog says otherwise:
2595808 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.campaign.FactionAPI.setRelationship(String, float)" because the return value of "com.fs.starfarer.api.campaign.SectorAPI.getFaction(String)" is null
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.campaign.FactionAPI.setRelationship(String, float)" because the return value of "com.fs.starfarer.api.campaign.SectorAPI.getFaction(String)" is null
        at data.scripts.campaign.colonies.VayraColonialManager.<init>(VayraColonialManager.java:125) ~[?:?]
        at data.scripts.VayraMergedModPlugin.onNewGameAfterTimePass(VayraMergedModPlugin.java:332) ~[?:?]
        at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source) ~[port_obf.jar:?]

So, null-guard everything and make it safe so it least it doesn't crash. And the two new methods -
safeChangeRelationshipForFaction() and safeGetRelationshipForFactionToFaction() should do.
The rest of the changes are just necessary baggage for it to look alright and work out fine.