Fix some crash from discord regarding null skills (#29)
* Replace all occurances of 'fighter_doctrine' with 'carrier_group'

While I fixed this in the code a long time ago, turns out i did not fix the data leaks...

So after a certain crash happened
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.loading.SkillSpec.isAptitudeEffect()" because the return value of "com.fs.starfarer.campaign.CharacterStats$SkillLevel.getSkill()" is null
    at com.fs.starfarer.campaign.CharacterStats.refreshCharacterStatsEffects(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.campaign.CharacterStats.refreshCharacterStatsEffects(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.api.impl.campaign.fleets.FleetFactoryV3.addCommanderSkills(FleetFactoryV3.java:1192) ~[starfarer.api.jar:?]
    at com.fs.starfarer.api.impl.campaign.fleets.FleetFactoryV3.addCommanderSkills(FleetFactoryV3.java:1904) ~[starfarer.api.jar:?]
    at data.scripts.campaign.intel.VayraPersonBountyIntel.spawnFleet(VayraPersonBountyIntel.java:1071) ~[?:?]
    at data.scripts.campaign.intel.VayraPersonBountyIntel.<init>(VayraPersonBountyIntel.java:205) ~[?:?]
    at data.scripts.campaign.intel.VayraPersonBountyManager.createEvent(VayraPersonBountyManager.java:326) ~[?:?]
    at data.scripts.campaign.intel.VayraPersonBountyManager.advance(VayraPersonBountyManager.java:300) ~[?:?]
    at data.scripts.VayraMergedModPlugin.onNewGameAfterTimePass(VayraMergedModPlugin.java:343) ~[?:?]
    at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source) ~[port_obf.jar:?]

it became clear that the FleetFactoryV3 was adding levels to `null` skills. And using no-longer-existant skills in faction files
is most likely the culprit.

So simply replace all occurances of 'fighter_doctrine' with 'carrier_group' as I did previously in the code.

* Get rid of commented-out FIGHTER_DOCTRINE references