Fix a crash reported on discord
The stacktrace is as follows:

79139334 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.loading.IndustrySpecAPI.getBuildTime()" because "upgrade" is null
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.loading.IndustrySpecAPI.getBuildTime()" because "upgrade" is null
        at com.fs.starfarer.api.impl.campaign.econ.impl.BaseIndustry.startUpgrading(BaseIndustry.java:572) ~[starfarer.api.jar:?]
        at data.scripts.campaign.colonies.VayraColonialManager.pickNextUpgrade(VayraColonialManager.java:589) ~[?:?]
        at data.scripts.campaign.fleets.VayraPopularFrontManager.advance(VayraPopularFrontManager.java:106) ~[?:?]
        at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.BaseGameState.traverse(Unknown Source) ~[port_obf.jar:?]
        at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
        at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]

After looking into the code, it really looked like this is a plausible scenario to happen:

        if (upgrade != null && market.hasIndustry(upgrade)) {
            market.getIndustry(upgrade).startUpgrading();
            log.info(String.format("upgrading %s on %s", upgrade, market.getName()));
            return;
        }

if the market.getIndustry(upgrade) returns null, invoking .startUpgrading() on it will surely hit a NPE.

So, I made sure it's nullguarded now, so at least it won't crash anymore.
Ideally a new industry should be repicked but... lets just go with not crashing for the time being.

AMEND:
also include jar with the fix for, who knows what reason.